os: linux
dist: trusty
sudo: required
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- make travis
before_install:
- openssl aes-256-cbc -K $encrypted_41103fb4d715_key -iv $encrypted_41103fb4d715_iv
  -in config.ini.enc -out bot/config.ini -d
notifications:
  webhooks:
    urls:
    - https://integrations.bonbotics.io/travis/webhook/2Xp5VtTcrNNLtIMd9zfTEIIE1AJHZRsHEOgASbWe0UM
    on_success: never
    on_failure: always
    on_start: never
deploy:
  provider: heroku
  api_key:
    secure: QApxz2stHunpKFER3hm0YgeegvKNIv2gzoLhP1AaPTzuHwuUDnWmdza2zOigdfGQ40UO2yidXhdfJkEIOGXF9j/1hWLbd+f+CBYuPmYOjchFXaKk+Sli8AxSg+43E2JeeoaSZ3cj97xjf3UlX+/0Hc5K++fPEUnhyAYlKqI3Tw/d2lWyH2adL/Tk6gqo9XlT1Ids84hq8JPiCYLIgAeX1sujWPMK4E7mvytaouZMxd/finKV7cmI5FDiak/wBBvjptVfqntyNH1Rogfgk8jwrQ923E7S9vTjaw+ntnUzI4kV/Dv9oxGVc2baPoqROO+qGgRmHHmeChyRkmO3frxi5VuprDtdkxVXknm8K8X/xqR84s1xN4V5gkWbz1om35qsM9KWSHpyodDbJq+cXMdkzpI3KXIgiWDoKEox37mlt7+abpYsQOVlQR5vbe0jAH/muNmGlT4txD5SzCe7ix2DmKIU4S5TVtrBJzwISJmY2Q+bRWDjoDAJAf1ccQOQ9HHFUQQVu2AqONJA+WsNC3cZvgQK41MBK5+ustcUgOWCyDlkD+PYwqA188HHqtm3HwCj6YhybAiOEpIIuxGKBP8RH9th7IawWi6ZMuGL+T6yqRJNYoftWJbEHUx5yiM6deJ4Od5njuqAg6FAuILjzqbvrD3sIREdzJxWJvFTfoa8wEU=
  app: projeto-chatbot
after_success:
- codecov
