os: linux
dist: trusty
sudo: required
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- make full
before_install:
- openssl aes-256-cbc -K $encrypted_41103fb4d715_key -iv $encrypted_41103fb4d715_iv
  -in config.ini.enc -out bot/config.ini -d
